path: data
train: train/images
val: valid/images
test: test/images

nc: 2
names: ["empty", "occupied"]

roboflow:
  workspace: patterns-mq36m
  project: parking-6eoex
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/patterns-mq36m/parking-6eoex/dataset/1
